// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsimfqhzuwubutfnhrxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zaW1mcWh6dXd1YnV0Zm5ocnhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzOTU0NzUsImV4cCI6MjA4OTk3MTQ3NX0.8mUKD8qytH0YfSGsvjS2jZZdndwyfDUFM74R234HqPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});